Import Debian changes 2.47-3
dnsmasq (2.47-3) unstable; urgency=low
.
   * Fix bashism in init script. (closes: #514397)
   * Tweak logging in init script.

diff --git a/init b/init
--- a/init
+++ b/init
@@ -30,7 +30,11 @@ if [ -f /lib/lsb/init-functions ]; then
          . /lib/lsb/init-functions
 else
          log_warning_msg () {
-            echo -n " ($@)"
+            echo "${@}."
+         }
+
+         log_success_msg () {
+            echo "${@}."
          }
 
          log_daemon_msg () {
@@ -38,7 +42,13 @@ else
          }
 
 	 log_end_msg () {
-            echo "."; 
+            if [ $1 -eq 0 ]; then
+              echo "."
+            elif [ $1 -eq 255 ]; then
+              /bin/echo -e " (warning)."
+            else
+              /bin/echo -e " failed!"
+            fi
          }
 fi
 
@@ -80,8 +90,7 @@ start()
         # /var/run/dnsmasq exists here as well as in postinst
         if [ ! -d /var/run/dnsmasq ]; then
            mkdir /var/run/dnsmasq || return 2
-           chown dnsmasq /var/run/dnsmasq || return 2
-           chgrp nogroup /var/run/dnsmasq || return 2
+           chown dnsmasq:nogroup /var/run/dnsmasq || return 2
         fi
 
 	start-stop-daemon --start --quiet --pidfile /var/run/dnsmasq/$NAME.pid --exec $DAEMON --test > /dev/null || return 1
@@ -164,12 +173,10 @@ case "$1" in
 			exit 0
 			;;
 		1)
-			log_warning_msg "already running"
-			log_end_msg 0
+			log_success_msg "(already running)"
 			exit 0
 			;;
 		*)
-			log_warning_msg "failed"
 			log_end_msg 1
 			exit 1
 			;;
@@ -182,7 +189,7 @@ case "$1" in
 	fi
 	stop
         RETVAL="$?"
-	if [ "$ENABLED" == "0" ]; then
+	if [ "$ENABLED" = "0" ]; then
 	    case "$RETVAL" in
 	       0) log_daemon_msg "Stopping $DESC" "$NAME"; log_end_msg 0 ;;
             esac 
@@ -190,8 +197,8 @@ case "$1" in
 	fi
 	case "$RETVAL" in
 		0) log_end_msg 0 ; exit 0 ;;
-		1) log_warning_msg "not running" ; log_end_msg 0 ; exit 0 ;;
-		*) log_warning_msg "failed" ; log_end_msg 1 ; exit 1 ;;
+		1) log_warning_msg "(not running)" ; exit 0 ;;
+		*) log_end_msg 1; exit 1 ;;
 	esac
 	;;
   restart|force-reload)
@@ -208,20 +215,13 @@ case "$1" in
 					start_resolvconf
 					exit 0
 					;;
-				1)
-					log_warning_msg "failed -- old process is still running"
-					log_end_msg 1
-					exit 1
-					;;
-				*)
-					log_warning_msg "failed to start"
+			        *)
 					log_end_msg 1
 					exit 1
 					;;
 			esac
 			;;
 		*)
-			log_warning_msg "failed to stop"
 			log_end_msg 1
 			exit 1
 			;;
@@ -231,10 +231,10 @@ case "$1" in
 	log_daemon_msg "Checking $DESC" "$NAME"
 	status
 	case "$?" in
-		0) log_warning_msg "running" ; log_end_msg 0; exit 0 ;;
-		1) log_warning_msg "dead, pid file exists" ; log_end_msg 1; exit 1 ;;
-		3) log_warning_msg "not running" ; log_end_msg 3; exit 3 ;;
-		*) log_warning_msg "unknown" ; log_end_msg 4; exit 4 ;;
+		0) log_success_msg "(running)" ; exit 0 ;;
+		1) log_success_msg "(dead, pid file exists)" ; exit 1 ;;
+		3) log_success_msg "(not running)" ; exit 3 ;;
+		*) log_success_msg "(unknown)" ; exit 4 ;;
 	esac
 	;;
   *)
